### PR TITLE
updated eslint to 8

### LINKED ISSUE #9: Require eslint 8 (and use eslint 8!)

### PR DESCRIPTION
**Pull request by andolf**
closes #9

### CODE REVIEW

**Comment by markusn** [comment]
@andolf have you tested this on one of our bigger projects?

**Comment by andolf** [comment]
> @andolf have you tested this on one of our bigger projects?

Nope! Will try it out later today hopefully.

**Comment by andolf** [comment]
@markusn Running this in solveig only produces errors for `comma-dangle` since they're still running `0.0.4`.

Should be fine.

**Comment by andolf** [comment]
Tried on `exp-account` which was running `eslint@7`; install stops because of incompatible eslint versions. Seems to be the correct way of handling things.

**Review by paed01 — APPROVED** [review]

**Pull request merged**
